[package]
name = "usb-device"
description = "Experimental device-side USB stack for embedded devices."
version = "0.2.0"
edition = "2018"
readme = "README.md"
keywords = ["no-std", "embedded", "usb"]
license = "MIT"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]
repository = "https://github.com/mvirkkunen/usb-device"

[dev-dependencies]
libusb = "0.3.0"
rand = "0.6.1"

[[test]]
name = "test_class_host"
path = "tests/test_class_host/main.rs"
harness = false

[features]
bigger-control-buffer = []
